# Exercise 1.04: Tic-Tac-Toe Static Evaluation with a Heuristic Function
In this exercise, you will be performing a static evaluation on the tic-tac-toe game using a heuristic function.

1.- Reuse the code from Steps 1–5 of Activity 1.01

In [1]:
# Reuse the code from Steps 2–4 of the Activity 1.02
import numpy as np
from random import choice

combo_indices = [['0,1,2'], ['0,3,6'], ['0,4,8'], ['3,4,5'], ['6,7,8'], ['1,4,7'], ['2,5,8'], ['2,4,6']]

EMPTY = "-"
IA = "X"
P = "O"

board = [[EMPTY,EMPTY,EMPTY],[EMPTY,EMPTY,EMPTY],[EMPTY,EMPTY,EMPTY]]

def boardP(board):
    print("\n")
    board_r = np.array(board)
    print(board_r)
    print("\n")
    
boardP(board)

def player_move(board, row, col):
    if board[row][col] != IA:
        board[row][col] = P
        return board
    else:
        return "Espacio ocupado"

moves = list()
move_list = list()
def map_all_moves(move_list):
    for i in move_list:
        moves.append(all_moves_from_board(board, move_list))
    return moves
    
moves = map_all_moves(move_list)
print(moves)

IA_wins=list()
P_wins=list()
draws = list()
boards_state=list()
def filter_wins(winner):
    if winner == IA:
        IA_wins.append(9-len(move_list))
        P_wins.append(0)
        draws.append(0)
    elif winner == P:
        P_wins.append(9-len(move_list))
        IA_wins.append(0)
        draws.append(0)
    else:
        draws.append(9-len(move_list))
        P_wins.append(0)
        IA_wins.append(0)
    boards_state.append(board)
    
def count_possibilities():
    IA_counts = 0
    P_counts = 0
    draws_counts = 0
    c = 1
    for i in IA_wins:
        print("step "+str(c)+". moves: "+str(i))
        if i != 0:
            IA_counts += 1
        c += 1
    c = 1
    for i in P_wins:
        print("step "+str(c)+". moves: "+str(i))
        if i != 0:
            P_counts += 1
        c += 1
    c = 1
    for i in draws:
        print("step "+str(c)+". moves: "+str(i))
        if i != 0:
            draws_counts += 1
        c += 1
    print("First player wins -IA-: "+str(IA_counts))
    print("Second player wins -P-: "+str(P_counts))
    print("Draw: "+str(draws_counts))
    print("Total: "+str(draws_counts+IA_counts+P_counts))

count_possibilities()

def game_won_by(board):
    won = False
    winner = "Nothing"
    for i in combo_indices:
        if i == ['0,1,2']:
            if board[0][0]==board[0][1] and board[0][1]==board[0][2] and board[0][2]!=EMPTY:
                print("Ganador: "+board[0][0])
                won = True
                winner = str(board[0][0])
                break
        elif i == ['3,4,5']:
            if board[1][0] == board[1][1] and board[1][1] == board[1][2] and board[1][2] != EMPTY:
                print("Ganador: "+board[1][0])
                won = True
                winner = str(board[1][0])
                #print("Winn: " + winner)
                break
        elif i == ['6,7,8']:
            if board[2][0] == board[2][1] and board[2][1] == board[2][2] and board[2][2] != EMPTY:
                print("Ganador: "+board[2][0])
                won = True
                winner = str(board[2][0])
                #print("Winn: " + winner)
                break
        elif i == ['0,4,8']:
            if board[0][0] == board[1][1] and board[1][1] == board[2][2] and board[2][2] != EMPTY:
                print("Ganador: "+board[0][0])
                won = True
                winner = str(board[0][0])
                #print("Winn: " + winner)
                break
        elif i == ['1,4,7']:
            if board[0][1] == board[1][1] and board[1][1] == board[2][1] and board[2][1] != EMPTY:
                print("Ganador: "+board[1][1])
                won = True
                winner = str(board[1][1])
                #print("Winn: " + winner)
                break
        elif i == ['0,3,6']:
            if board[0][0] == board[1][0] and board[1][0] == board[2][0] and board[2][0] != EMPTY:
                print("Ganador: "+board[1][0])
                won = True
                winner = str(board[1][0])
                #print("Winn: " + winner)
                break
        elif i == ['2,5,8']:
            if board[0][2] == board[1][2] and board[1][2] == board[2][2] and board[2][2] != EMPTY:
                print("Ganador: "+board[1][2])
                won = True
                winner = str(board[1][2])
                #print("Winn: " + winner)
                break
        elif i == ['2,4,6']:
            if board[0][2] == board[1][1] and board[1][1] == board[2][0] and board[2][0] != EMPTY:
                print("Ganador: "+board[1][1])
                won = True
                winner = str(board[1][1])
                #print("Winn: " + winner)
                break
        else:
            print("Paso")
    
    return won, winner
    
game_won_by(board)

move_list = list()

def all_moves_from_board(board, move_list):
    k = 0
    move_list.clear()
    for i in range(3):
        for j  in range(3):
            if board[i][j] == EMPTY:
                move_list.append(str(k))
            k+=1

all_moves_from_board(board, move_list)

def player_can_win(board, move_list):
    c_ia, c_empty, to_win_p, k, founded = 0, 0, "", 0, False
    
    if coded_move(move_list)>6 and coded_move(move_list)<=9:
        print("Coded move")
        
    if (board[0][0] == IA and board[1][1] == EMPTY) or (board[0][2] == IA and board[1][1] == EMPTY) or (board[2][0] == IA and board[1][1] == EMPTY) or (board[2][2] == IA and board[1][1] == EMPTY):
        print("Es recomendable escoger el centro")
    
    #FILAS
    for i in range(3):
        for j in range(3):
            if i == 0:
                if board[i][j] == P:
                    c_ia += 1
                if board[i][j] == EMPTY:
                    c_empty += 1
                    to_win_ia = str(k)
                if c_ia == 2 and c_empty == 1:
                    print("Escoge esto para ganar: "+to_win_ia)
                    founded = True
            k += 1
            
    if founded == False:
        c_ia, c_empty, to_win_ia, k = 0, 0, "", 0

        #FILAS
        for i in range(3):
            for j in range(3):
                if i == 1:
                    if board[i][j] == P:
                        c_ia += 1
                    if board[i][j] == EMPTY:
                        c_empty += 1
                        to_win_ia = str(k)
                    if c_ia == 2 and c_empty == 1:
                        print("Escoge esto para ganar: "+to_win_ia)
                        founded = True
                k += 1
                
    if founded == False:
        c_ia, c_empty, to_win_ia, k = 0, 0, "", 0

        #FILAS
        for i in range(3):
            for j in range(3):
                if i == 2:
                    if board[i][j] == P:
                        c_ia += 1
                    if board[i][j] == EMPTY:
                        c_empty += 1
                        to_win_ia = str(k)
                    if c_ia == 2 and c_empty == 1:
                        print("Escoge esto para ganar: "+to_win_ia)
                        founded = True
                k += 1
                
    if founded == False:
        c_ia, c_empty, to_win_ia, k = 0, 0, "", 0        
        #COLUMNAS
        for i in range(3):
            for j in range(3):
                if j == 0:
                    if board[i][j] == P:
                        c_ia += 1
                    if board[i][j] == EMPTY:
                        c_empty += 1
                        to_win_ia = str(k)
                    if c_ia == 2 and c_empty == 1:
                        print("Escoge esto para ganar: "+to_win_ia)
                        founded = True
                k += 1
    
    if founded == False:
        c_ia, c_empty, to_win_ia, k = 0, 0, "", 0

        for i in range(3):
            for j in range(3):
                if j == 1:
                    if board[i][j] == P:
                        c_ia += 1
                    if board[i][j] == EMPTY:
                        c_empty += 1
                        to_win_ia = str(k)
                    if c_ia == 2 and c_empty == 1:
                        print("Escoge esto para ganar: "+to_win_ia)
                        founded = True
                k += 1
    
    if founded == False:
        c_ia, c_empty, to_win_ia, k = 0, 0, "", 0

        for i in range(3):
            for j in range(3):
                if j == 2:
                    if board[i][j] == P:
                        c_ia += 1
                    if board[i][j] == EMPTY:
                        c_empty += 1
                        to_win_ia = str(k)
                    if c_ia == 2 and c_empty == 1:
                        print("Escoge esto para ganar: "+to_win_ia)
                        founded = True
                k += 1
                
    #DIAGONALES
    if founded == False:
        c_ia, c_empty, to_win_ia, k = 0, 0, "", 0

        for i in range(3):
            for j in range(3):
                if (i == 0 and j == 0) or (i == 1 and j == 1) or (i == 2 and j == 2):
                    if board[i][j] == P:
                        c_ia += 1
                    if board[i][j] == EMPTY:
                        c_empty += 1
                        to_win_ia = str(k)
                    if c_ia == 2 and c_empty == 1:
                        print("Escoge esto para ganar: "+to_win_ia)
                        founded = True
                k += 1
                
    if founded == False:
        c_ia, c_empty, to_win_ia, k = 0, 0, "", 0

        for i in range(3):
            for j in range(3):
                if (i == 0 and j == 2) or (i == 1 and j == 1) or (i == 2 and j == 0):
                    if board[i][j] == P:
                        c_ia += 1
                    if board[i][j] == EMPTY:
                        c_empty += 1
                        to_win_ia = str(k)
                    if c_ia == 2 and c_empty == 1:
                        print("Escoge esto para ganar: "+to_win_ia)
                        founded = True
                k += 1
    
    return founded

def ai_move(board, move_list):
    
    c_ia, c_empty, to_win_ia, k, founded, secure_move, center_move = 0, 0, "", 0, False, False, False
    
    if (board[0][0] == P and board[1][1] == EMPTY) or (board[0][2] == P and board[1][1] == EMPTY) or (board[2][0] == P and board[1][1] == EMPTY) or (board[2][2] == P and board[1][1] == EMPTY):
        print("Movimiento al centro.")
        to_win_ia == '4'
        center_move = True
    
    
    #MOVIMIENTOS SEGUROS
    if center_move == False:
        c_empty, to_win_ia, k = 0, "", 0
        
        #FILAS
        for i in range(3):
            for j in range(3):
                if i == 0:
                    if board[i][j] == EMPTY:
                        c_empty += 1
                    if c_empty >= 2 and k<3:
                        print("Movimiento seguro")
                        to_win_ia = str(k)
                        secure_move = True
                        break
                k += 1
                    
    if secure_move == False:
        c_empty, to_win_ia, k = 0, "", 0
        
        for i in range(3):
            for j in range(3):
                if i == 1:
                    if board[i][j] == EMPTY:
                        c_empty += 1
                        to_win_ia = str(k)
                    if  c_empty >= 2:
                        print("Movimiento seguro")
                        secure_move = True
                        break
                k += 1
                
    if secure_move == False:
        c_empty, to_win_ia, k = 0, "", 0
        
        for i in range(3):
            for j in range(3):
                if i == 2:
                    if board[i][j] == IA:
                        c_ia += 1
                    if board[i][j] == EMPTY:
                        c_empty += 1
                        to_win_ia = str(k)
                    if c_ia == 2 and c_empty == 1:
                        print("Movimiento seguro")
                        secure_move = True
                        break
                k += 1
    #COLUMNAS
    if secure_move == False:
        c_empty, to_win_ia, k = 0, "", 0
        
        for i in range(3):
            for j in range(3):
                if j == 0:
                    if board[i][j] == EMPTY:
                        c_empty += 1
                        to_win_ia = str(k)
                    if c_empty >= 2:
                        print("Movimiento seguro")
                        secure_move = True
                        break
                k += 1
    
    if secure_move == False:
        c_empty, to_win_ia, k = 0, "", 0
                
        for i in range(3):
                for j in range(3):
                    if j == 1:
                        if board[i][j] == EMPTY:
                            c_empty += 1
                            to_win_ia = str(k)
                        if c_empty >=2:
                            print("Movimiento seguro")
                            secure_move = True
                            break
                    k += 1
                    
    if secure_move == False:
        c_empty, to_win_ia, k = 0, "", 0
                
        for i in range(3):
                for j in range(3):
                    if j == 2:
                        if board[i][j] == IA:
                            c_ia += 1
                        if board[i][j] == EMPTY:
                            c_empty += 1
                            to_win_ia = str(k)
                        if c_ia == 2 and c_empty == 1:
                            print("Movimiento seguro")
                            secure_move = True
                            break
                    k += 1
    #DIAGONALES
    if secure_move == False:
        c_empty, to_win_ia, k = 0, "", 0
        
        for i in range(3):
                for j in range(3):
                    if (i == 0 and j == 0) or (i == 1 and j == 1) or (i == 2 and j == 2):
                        if board[i][j] == EMPTY:
                            c_empty += 1
                            to_win_ia = str(k)
                        if c_empty >= 2:
                            print("Movimiento seguro")
                            secure_move = True
                            break
                    k += 1
                    
    if secure_move == False:
        c_empty, to_win_ia, k = 0, "", 0               
        for i in range(3):
                for j in range(3):
                    if (i == 0 and j == 2) or (i == 1 and j == 1) or (i == 2 and j == 0):
                        if board[i][j] == IA:
                            c_ia += 1
                        if board[i][j] == EMPTY:
                            c_empty += 1
                            to_win_ia = str(k)
                        if c_ia == 2 and c_empty == 1:
                            print("Movimiento seguro")
                            secure_move = True
                            break
                    k += 1
    #======================================================================    
    
    if secure_move == False:
    #FILAS
        c_ia, c_empty, to_win_ia, k = 0, 0, "", 0
        for i in range(3):
            for j in range(3):
                if i == 0:
                    if board[i][j] == IA:
                        c_ia += 1
                    if board[i][j] == EMPTY:
                        c_empty += 1
                        to_win_ia = str(k)
                    if c_ia == 2 and c_empty == 1:
                        print("IA Escoge esto para ganar: "+to_win_ia)
                        founded = True
                        break
                k += 1
            
    if founded == False:
        c_ia, c_empty, to_win_ia, k = 0, 0, "", 0

        #FILAS
        for i in range(3):
            for j in range(3):
                if i == 1:
                    if board[i][j] == IA:
                        c_ia += 1
                    if board[i][j] == EMPTY:
                        c_empty += 1
                        to_win_ia = str(k)
                    if c_ia == 2 and c_empty == 1:
                        print("IA Escoge esto para ganar: "+to_win_ia)
                        founded = True
                        break
                k += 1
                
    if founded == False:
        c_ia, c_empty, to_win_ia, k = 0, 0, "", 0

        #FILAS
        for i in range(3):
            for j in range(3):
                if i == 2:
                    if board[i][j] == IA:
                        c_ia += 1
                    if board[i][j] == EMPTY:
                        c_empty += 1
                        to_win_ia = str(k)
                    if c_ia == 2 and c_empty == 1:
                        print("IA Escoge esto para ganar: "+to_win_ia)
                        founded = True
                        break
                k += 1
                
    if founded == False:
        c_ia, c_empty, to_win_ia, k = 0, 0, "", 0        
        #COLUMNAS
        for i in range(3):
            for j in range(3):
                if j == 0:
                    if board[i][j] == IA:
                        c_ia += 1
                    if board[i][j] == EMPTY:
                        c_empty += 1
                        to_win_ia = str(k)
                    if c_ia == 2 and c_empty == 1:
                        print("IA Escoge esto para ganar: "+to_win_ia)
                        founded = True
                        break
                k += 1
    
    if founded == False:
        c_ia, c_empty, to_win_ia, k = 0, 0, "", 0

        for i in range(3):
            for j in range(3):
                if j == 1:
                    if board[i][j] == IA:
                        c_ia += 1
                    if board[i][j] == EMPTY:
                        c_empty += 1
                        to_win_ia = str(k)
                    if c_ia == 2 and c_empty == 1:
                        print("IA Escoge esto para ganar: "+to_win_ia)
                        founded = True
                        break
                k += 1
    
    if founded == False:
        c_ia, c_empty, to_win_ia, k = 0, 0, "", 0

        for i in range(3):
            for j in range(3):
                if j == 2:
                    if board[i][j] == IA:
                        c_ia += 1
                    if board[i][j] == EMPTY:
                        c_empty += 1
                        to_win_ia = str(k)
                    if c_ia == 2 and c_empty == 1:
                        print("IA Escoge esto para ganar: "+to_win_ia)
                        founded = True
                        break
                k += 1
                
    #DIAGONALES
    if founded == False:
        c_ia, c_empty, to_win_ia, k = 0, 0, "", 0

        for i in range(3):
            for j in range(3):
                if (i == 0 and j == 0) or (i == 1 and j == 1) or (i == 2 and j == 2):
                    if board[i][j] == IA:
                        c_ia += 1
                    if board[i][j] == EMPTY:
                        c_empty += 1
                        to_win_ia = str(k)
                    if c_ia == 2 and c_empty == 1:
                        print("IA Escoge esto para ganar: "+to_win_ia)
                        founded = True
                        break
                k += 1
                
    if founded == False:
        c_ia, c_empty, to_win_ia, k = 0, 0, "", 0

        for i in range(3):
            for j in range(3):
                if (i == 0 and j == 2) or (i == 1 and j == 1) or (i == 2 and j == 0):
                    if board[i][j] == IA:
                        c_ia += 1
                    if board[i][j] == EMPTY:
                        c_empty += 1
                        to_win_ia = str(k)
                    if c_ia == 2 and c_empty == 1:
                        print("IA Escoge esto para ganar: "+to_win_ia)
                        founded = True
                        break
                k += 1
    
    if founded or center_move or secure_move:
        index = to_win_ia
        if index == '6':
            index = choice(move_list)
    else:
        index = choice(move_list)
    
    if index == '0':
        board[0][0] = IA
    elif index == '1':
        board[0][1] = IA
    elif index == '2':
        board[0][2] = IA
    elif index == '3':
        board[1][0] = IA
    elif index == '4':
        board[1][1] = IA
    elif index == '5':
        board[1][2] = IA
    elif index == '6':
        board[2][0] = IA
    elif index == '7':
        board[2][1] = IA
    elif index == '8':
        board[2][2] = IA
    else:
        print("Next")
        
def coded_move(move_list):
    return len(move_list)
        
# Test the application
board = [[EMPTY,EMPTY,EMPTY],[EMPTY,EMPTY,EMPTY],[EMPTY,EMPTY,EMPTY]]
def game_loop(board, utilities_matrix):
    #board = [[EMPTY,EMPTY,EMPTY],[EMPTY,EMPTY,EMPTY],[EMPTY,EMPTY,EMPTY]]
    empty_cell_count = 9
    won = False
    winner = "False"
    next_move = False
    while empty_cell_count > 0 and won == False:
        all_moves_from_board(board,move_list)
        print(move_list)
        if empty_cell_count % 2 == 1:
            ai_move(board, move_list)
            print("===IA MOVE ===============================")
            generate_add_score(0, 0, utilities_matrix)
            boardP(board)
            won, winner = game_won_by(board)
        else:
            print("===PLAYER MOVE ===============================")
            next_move = player_can_win(board, move_list)
            if next_move:
                print("Usted puede ganar el juego")
            
            row = int(input('Fila: '))
            col = int(input('Columna: '))
            
            while isEmptyBoard(board, row, col) != 0:
                print("Espacio ocupado, escoga otro.")
                row = int(input('Fila: '))
                col = int(input('Columna: '))
                
            generate_add_score(row, col, utilities_matrix)
            board = player_move(board, row, col)
            boardP(board)
            won, winner = game_won_by(board)
        empty_cell_count = empty_cell_count - 1
                
    print("Juego terminado.")
    return winner



[['-' '-' '-']
 ['-' '-' '-']
 ['-' '-' '-']]


[]
First player wins -IA-: 0
Second player wins -P-: 0
Draw: 0
Total: 0


2.- Create a function that takes the board as input and returns $0$ if the cell is empty, and $-1$ if it's not empty

In [2]:
def isEmptyBoard(board, row, col):
    if board[row][col] != EMPTY:
        return -1
    else:
        return 0

3.- Create a function that takes the utility vector of possible moves, takes three indices inside the utility vector representing a triple, and returns a function.

  > **Hints**  
  > the returned function will expect a `points` parameter and the `utilities` vector as input and will add points to each cell in $(i, j, k)$, as long as the original value of that cell is non-negative $(>=0)$. In other words, we increased the utility of empty cells only.

In [3]:
def generate_add_score(row, col, utilities_matrix):
    count_empty, count_ia, empty_cell = 0, 0, 0
    for i in range(3):
        for j in range(3):
            #FILAS
            if i == 0:
                if board[i][j] == IA:
                    count_empty += 1
                if board[i][j] == EMPTY:
                    empty_cell = j
                    count_empty += 1
                if count_empty == 1 and count_ia == 2:
                    utilities_matrix[i][empty_cell] += 1000
            if i == 1:
                if board[i][j] == IA:
                    count_empty += 1
                if board[i][j] == EMPTY:
                    empty_cell = j
                    count_empty += 1
                if count_empty == 1 and count_ia == 2:
                    utilities_matrix[i][empty_cell] += 1000
            if i == 2:
                if board[i][j] == IA:
                    count_empty += 1
                if board[i][j] == EMPTY:
                    empty_cell = j
                    count_empty += 1
                if count_empty == 1 and count_ia == 2:
                    utilities_matrix[i][empty_cell] += 1000
                    
    count_empty, count_ia, empty_cell = 0, 0, 0
    for i in range(3):
        for j in range(3):
            #COLUMNAS
            if j == 0:
                if board[i][j] == IA:
                    count_empty += 1
                if board[i][j] == EMPTY:
                    empty_cell = j
                    count_empty += 1
                if count_empty == 1 and count_ia == 2:
                    utilities_matrix[i][empty_cell] += 1000
            if j == 1:
                if board[i][j] == IA:
                    count_empty += 1
                if board[i][j] == EMPTY:
                    empty_cell = j
                    count_empty += 1
                if count_empty == 1 and count_ia == 2:
                    utilities_matrix[i][empty_cell] += 1000
            if j == 2:
                if board[i][j] == IA:
                    count_empty += 1
                if board[i][j] == EMPTY:
                    empty_cell = j
                    count_empty += 1
                if count_empty == 1 and count_ia == 2:
                    utilities_matrix[i][empty_cell] += 1000
                    
    #DIAGONAL
    if board[0][0] == IA and board[1][1] == IA and board[2][2] == EMPTY:
        utilities_matrix[2][2] += 100
    if board[0][0] == IA and board[1][1] == EMPTY and board[2][2] == IA:
        utilities_matrix[1][1] += 100
    if board[0][0] == EMPTY and board[1][1] == IA and board[2][2] == IA:
        utilities_matrix[1][1] += 100
        
    if board[0][1] == IA and board[1][1] == IA and board[2][0] == EMPTY:
        utilities_matrix[2][2] += 100
    if board[0][1] == IA and board[1][1] == EMPTY and board[2][0] == IA:
        utilities_matrix[1][1] += 100
    if board[0][1] == EMPTY and board[1][1] == IA and board[2][0] == IA:
        utilities_matrix[1][1] += 100
        
    count_empty, count_ia, empty_cell = 0, 0, 0
    for i in range(3):
        for j in range(3):
            #FILAS
            if i == 0:
                if board[i][j] == P:
                    count_empty += 1
                if board[i][j] == EMPTY:
                    empty_cell = j
                    count_empty += 1
                if count_empty == 1 and count_ia == 2:
                    utilities_matrix[i][empty_cell] += 1000
            if i == 1:
                if board[i][j] == P:
                    count_empty += 1
                if board[i][j] == EMPTY:
                    empty_cell = j
                    count_empty += 1
                if count_empty == 1 and count_ia == 2:
                    utilities_matrix[i][empty_cell] += 1000
            if i == 2:
                if board[i][j] == P:
                    count_empty += 1
                if board[i][j] == EMPTY:
                    empty_cell = j
                    count_empty += 1
                if count_empty == 1 and count_ia == 2:
                    utilities_matrix[i][empty_cell] += 1000
                    
    count_empty, count_ia, empty_cell = 0, 0, 0
    for i in range(3):
        for j in range(3):
            #COLUMNAS
            if j == 0:
                if board[i][j] == P:
                    count_empty += 1
                if board[i][j] == EMPTY:
                    empty_cell = j
                    count_empty += 1
                if count_empty == 1 and count_ia == 2:
                    utilities_matrix[i][empty_cell] += 1000
            if j == 1:
                if board[i][j] == P:
                    count_empty += 1
                if board[i][j] == EMPTY:
                    empty_cell = j
                    count_empty += 1
                if count_empty == 1 and count_ia == 2:
                    utilities_matrix[i][empty_cell] += 1000
            if j == 2:
                if board[i][j] == P:
                    count_empty += 1
                if board[i][j] == EMPTY:
                    empty_cell = j
                    count_empty += 1
                if count_empty == 1 and count_ia == 2:
                    utilities_matrix[i][empty_cell] += 1000
                    
    #DIAGONAL
    if board[0][0] == P and board[1][1] == P and board[2][2] == EMPTY:
        utilities_matrix[2][2] += 100
    if board[0][0] == P and board[1][1] == EMPTY and board[2][2] == P:
        utilities_matrix[1][1] += 100
    if board[0][0] == EMPTY and board[1][1] == P and board[2][2] == P:
        utilities_matrix[1][1] += 100
        
    if board[0][1] == P and board[1][1] == P and board[2][0] == EMPTY:
        utilities_matrix[2][2] += 100
    if board[0][1] == P and board[1][1] == EMPTY and board[2][0] == P:
        utilities_matrix[1][1] += 100
    if board[0][1] == EMPTY and board[1][1] == P and board[2][0] == P:
        utilities_matrix[1][1] += 100
        
    count_empty, count_ia, empty_cell = 0, 0, 0
    for i in range(3):
        for j in range(3):
            #FILAS
            if i == 0:
                if board[i][j] == IA:
                    count_empty += 1
                if board[i][j] == EMPTY:
                    empty_cell = j
                    count_empty += 1
                if count_empty == 2 and count_ia == 1:
                    utilities_matrix[i][empty_cell] += 10
            if i == 1:
                if board[i][j] == IA:
                    count_empty += 1
                if board[i][j] == EMPTY:
                    empty_cell = j
                    count_empty += 1
                if count_empty == 2 and count_ia == 1:
                    utilities_matrix[i][empty_cell] += 10
            if i == 2:
                if board[i][j] == IA:
                    count_empty += 1
                if board[i][j] == EMPTY:
                    empty_cell = j
                    count_empty += 1
                if count_empty == 2 and count_ia == 1:
                    utilities_matrix[i][empty_cell] += 10
                    
    count_empty, count_ia, empty_cell = 0, 0, 0
    for i in range(3):
        for j in range(3):
            #COLUMNAS
            if j == 0:
                if board[i][j] == IA:
                    count_empty += 1
                if board[i][j] == EMPTY:
                    empty_cell = j
                    count_empty += 1
                if count_empty == 2 and count_ia == 1:
                    utilities_matrix[i][empty_cell] += 10
            if j == 1:
                if board[i][j] == IA:
                    count_empty += 1
                if board[i][j] == EMPTY:
                    empty_cell = j
                    count_empty += 1
                if count_empty == 2 and count_ia == 1:
                    utilities_matrix[i][empty_cell] += 10
            if j == 2:
                if board[i][j] == IA:
                    count_empty += 1
                if board[i][j] == EMPTY:
                    empty_cell = j
                    count_empty += 1
                if count_empty == 2 and count_ia == 1:
                    utilities_matrix[i][empty_cell] += 10
                    
    #DIAGONAL
    if board[0][0] == IA and board[1][1] == IA and board[2][2] == EMPTY:
        utilities_matrix[2][2] += 10
    if board[0][0] == IA and board[1][1] == EMPTY and board[2][2] == IA:
        utilities_matrix[1][1] += 10
    if board[0][0] == EMPTY and board[1][1] == IA and board[2][2] == IA:
        utilities_matrix[1][1] += 10
        
    if board[0][1] == IA and board[1][1] == IA and board[2][0] == EMPTY:
        utilities_matrix[2][2] += 10
    if board[0][1] == IA and board[1][1] == EMPTY and board[2][0] == IA:
        utilities_matrix[1][1] += 10
    if board[0][1] == EMPTY and board[1][1] == IA and board[2][0] == IA:
        utilities_matrix[1][1] += 10
       
    count_empty, count_ia, empty_cell = 0, 0, 0
    for i in range(3):
        for j in range(3):
            if board[i][j] == EMPTY:
                count_empty += 1
                
    if count_empty >= 4:
        utilities_matrix = [[1,1,1],[1,1,1],[1,1,1]]
        count_empty, count_ia, empty_cell = 0, 0, 0
               
    print(utilities_matrix[0][1])
    boardP(utilities_matrix)

4.- Now, create the utility matrix belonging to any board constellation where you will add the `generate_add_score` function defined previously to update the score. You will also implement the rules that we discussed prior to this activity. These rules are as follows:
  * Two AI signs in a row, column, or diagonal, and the third cell is empty: +1000 for the empty cell.
  * The opponent has two signs in a row, column, or diagonal, and the third cell is empty: +100 for the empty cell.
  * One AI sign in a row, column, or diagonal, and the other two cells are empty: +10 for the empty cells.
  * No AI or opponent signs in a row, column, or diagonal: +1 for the empty cells.

In [4]:
utilities_matrix = [[0,0,0],[0,0,0],[0,0,0]]

5.- Create a function that selects the move with the highest utility value. If multiple moves have the same utility, the function returns both moves

In [5]:
def highestUtilityValue(utilities_matrix):
    return np.argmax(utilities_matrix)

6.- Run the application.

Output:

```
step 0. Moves: 1
step 1. Moves: 1
step 2. Moves: 8
step 3. Moves: 24
step 4. Moves: 144
step 5. Moves: 83
step 6. Moves: 214
step 7. Moves: 148
step 8. Moves: 172
First player wins: 504
Second player wins: 12
Draw 91
Total 607
```

In [6]:
winner = game_loop(board, utilities_matrix)
high_value = highestUtilityValue(utilities_matrix)
print("Max value in the index: "+str(high_value))
filter_wins(winner)
count_possibilities()

['0', '1', '2', '3', '4', '5', '6', '7', '8']
Movimiento seguro
===IA MOVE ===============================
1


[[1 1 1]
 [1 1 1]
 [1 1 1]]




[['-' '-' '-']
 ['-' '-' 'X']
 ['-' '-' '-']]


['0', '1', '2', '3', '4', '6', '7', '8']
===PLAYER MOVE ===============================
Coded move
Fila: 2
Columna: 0
1


[[1 1 1]
 [1 1 1]
 [1 1 1]]




[['-' '-' '-']
 ['-' '-' 'X']
 ['O' '-' '-']]


['0', '1', '2', '3', '4', '7', '8']
Movimiento al centro.
Movimiento seguro
===IA MOVE ===============================
1


[[1 1 1]
 [1 1 1]
 [1 1 1]]




[['-' '-' '-']
 ['-' 'X' 'X']
 ['O' '-' '-']]


['0', '1', '2', '3', '7', '8']
===PLAYER MOVE ===============================
Fila: 2
Columna: 2
1


[[1 1 1]
 [1 1 1]
 [1 1 1]]




[['-' '-' '-']
 ['-' 'X' 'X']
 ['O' '-' 'O']]


['0', '1', '2', '3', '7']
Movimiento seguro
IA Escoge esto para ganar: 3
===IA MOVE ===============================
1


[[1 1 1]
 [1 1 1]
 [1 1 1]]




[['-' '-' '-']
 ['X' 'X' 'X']
 ['O' '-' 'O']]


Ganador: X
Juego termin

By completing this exercise, we have observed that the AI is underperforming compared to our previous activity, Activity 1.03, Fixing the First and Second Moves of the AI to Make It Invincible. In this situation, hardcoding the first two moves was better than setting up the heuristic, but this is because we haven't set up the heuristic properly.